//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSlx.Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSlx.Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert type from {0} to Nullable&lt;{1}&gt;.
        /// </summary>
        internal static string CanTConvertTypeFromX0ToNullableX1 {
            get {
                return ResourceManager.GetString("CanTConvertTypeFromX0ToNullableX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert {0} from string to {1}.
        /// </summary>
        internal static string CanTConvertX0FromStringToX1 {
            get {
                return ResourceManager.GetString("CanTConvertX0FromStringToX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMethodName must be configured in order to use Delete.
        /// </summary>
        internal static string DeleteMethodNameMustBeConfiguredInOrderToU {
            get {
                return ResourceManager.GetString("DeleteMethodNameMustBeConfiguredInOrderToU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only numbers in this field..
        /// </summary>
        internal static string EnterOnlyNumbers {
            get {
                return ResourceManager.GetString("EnterOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only whole numbers, without cents..
        /// </summary>
        internal static string EnterOnlyWholeNumbers {
            get {
                return ResourceManager.GetString("EnterOnlyWholeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteUpdate passed empty &apos;keys&apos; array - is DataKeyNames defined?.
        /// </summary>
        internal static string ExecuteUpdatePassedEmptyKeysArrayIsDataKey {
            get {
                return ResourceManager.GetString("ExecuteUpdatePassedEmptyKeysArrayIsDataKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property expression for sort: {0}.
        /// </summary>
        internal static string InvalidPropertyExpressionForSortX0 {
            get {
                return ResourceManager.GetString("InvalidPropertyExpressionForSortX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} must be castable to ICollection.
        /// </summary>
        internal static string PropertyX0MustBeCastableToICollection {
            get {
                return ResourceManager.GetString("PropertyX0MustBeCastableToICollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlxEntityDataSource can only be used on an EntityBoundSmartPart.
        /// </summary>
        internal static string SlxEntityDataSourceCanOnlyBeUsedOnAnEntity {
            get {
                return ResourceManager.GetString("SlxEntityDataSourceCanOnlyBeUsedOnAnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} can&apos;t be found on type {1}.
        /// </summary>
        internal static string TheMethodX0CanTBeFoundOnTypeX1 {
            get {
                return ResourceManager.GetString("TheMethodX0CanTBeFoundOnTypeX1", resourceCulture);
            }
        }
    }
}
